# Generated by Django 5.2 on 2026-09-25 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='coursematerial',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__gte', 0)), name='material_file_size_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='coursematerial',
            constraint=models.CheckConstraint(condition=models.Q(('download_count__gte', 0)), name='material_download_count_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='feedback_rating_between_1_and_5'),
        ),
    ]
